"""
Falcon - Candidate Generation
Module: consolidator.py
Version: 1.1.0

Merge, deduplicate and enrich candidates into a Master Watchlist.
"""

from typing import List
import pandas as pd

from common.logger import get_logger
from candidate_generation.exceptions import ConsolidationError
from config import FALCON_VERSION

logger = get_logger("consolidator")


def consolidate(dataframes: List[pd.DataFrame]) -> pd.DataFrame:
    """
    Consolidate candidate DataFrames.

    Parameters
    ----------
    dataframes : List[pd.DataFrame]

    Returns
    -------
    Master Watchlist DataFrame
    """
    try:
        frames = [df for df in dataframes if df is not None and not df.empty]

        if not frames:
            return pd.DataFrame()

        merged = pd.concat(frames, ignore_index=True)

        logger.info("Merged %d rows.", len(merged))

        grouped = (
            merged.groupby("Symbol", dropna=False)
            .agg(
                Name=("Name", "first"),
                Strategy=("Strategy",
                          lambda x: ", ".join(sorted(set(map(str, x))))),
                Source=("Source",
                        lambda x: ", ".join(sorted(set(map(str, x))))),
                **{
                    "Generated On": ("Generated On", "max"),
                    "Generated By": ("Generated By", "first"),
                    "Status": ("Status", "first"),
                    "Remarks": ("Remarks", "first"),
                }
            )
            .reset_index()
        )

        grouped["Strategy Count"] = grouped["Strategy"].apply(
            lambda x: len([i for i in str(x).split(", ") if i])
        )

        grouped["Source Count"] = grouped["Source"].apply(
            lambda x: len([i for i in str(x).split(", ") if i])
        )

        front = [
            "Symbol",
            "Name",
            "Strategy",
            "Strategy Count",
            "Source",
            "Source Count",
            "Generated On",
            "Generated By",
            "Status",
            "Remarks",
        ]

        others = [c for c in grouped.columns if c not in front]

        result = grouped[front + others]

        logger.info(
            "Consolidated %d unique candidates.",
            len(result)
        )

        return result

    except Exception as ex:
        raise ConsolidationError(str(ex)) from ex
