"""
Falcon - Candidate Generation
Module: normalizer.py
Version: 1.1.0

Normalizes candidate DataFrames into the Falcon Base Schema.
"""

from datetime import datetime
from typing import Dict

import pandas as pd

from common.logger import get_logger
from candidate_generation.exceptions import DataNormalizationError
from config import FALCON_VERSION

logger = get_logger("normalizer")

# Falcon mandatory columns
BASE_SCHEMA = {
    "Name": "",
    "Symbol": "",
    "Strategy": "",
    "Source": "",
    "Generated On": "",
    "Generated By": "Falcon",
    "Status": "NEW",
    "Remarks": "",
}


def ensure_base_schema(df: pd.DataFrame) -> pd.DataFrame:
    """
    Ensure all Falcon mandatory columns exist.
    """
    df = df.copy()

    for column, default in BASE_SCHEMA.items():
        if column not in df.columns:
            df[column] = default

    return df


def attach_metadata(
    df: pd.DataFrame,
    strategy: str,
    source: str = "Screener",
    generated_by: str = "Candidate Generator",
) -> pd.DataFrame:
    """
    Populate Falcon metadata columns.
    """
    df = df.copy()

    today = datetime.now().strftime("%Y-%m-%d")

    df["Strategy"] = strategy
    df["Source"] = source
    df["Generated On"] = today
    df["Generated By"] = generated_by

    return df


def reorder_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Place Falcon columns first while preserving all
    remaining provider-specific columns.
    """
    required = list(BASE_SCHEMA.keys())

    remaining = [c for c in df.columns if c not in required]

    return df[required + remaining]


def normalize_dataframe(
    df: pd.DataFrame,
    strategy: str,
    source: str = "Screener",
) -> pd.DataFrame:
    """
    Complete Falcon normalization pipeline.
    """
    try:

        df = ensure_base_schema(df)

        df = attach_metadata(
            df,
            strategy=strategy,
            source=source,
        )

        df = reorder_columns(df)

        logger.info(
            "Normalized dataframe (%d rows).",
            len(df),
        )

        return df

    except Exception as ex:
        raise DataNormalizationError(str(ex)) from ex
